### ISSUE TITLE
 Error in 'append' command

### ISSUE THREAD

**Issue by rancher91** [doksu/TA-UserWatchlist#1]
When opening the dashboard there is now an error: Error in 'append' command: The 'append' command cannot be the first command in a search. Running Splunk v7.2.6. This worked on previous versions.

**Comment by doksu** [comment]
Thanks @rancher91, that's correct, Splunk has changed this is recent version. I'll publish an updated version of the app shortly.

**Comment by doksu** [comment]
New version released with this fixed for Splunk 7.3+: https://splunkbase.splunk.com/app/3591/
